---
title: "Performance comparison with other functional diversity packages"
output: rmarkdown::html_vignette
bibliography: performance.bib
vignette: >
  %\VignetteIndexEntry{Performance comparison with other functional diversity packages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This vignette presents some performance tests ran between `fundiversity` and other functional diversity packages. Note that to avoid the dependency on other packages, this vignette is [**pre-computed**](https://ropensci.org/technotes/2019/12/08/precompute-vignettes/).

# Other functions/packages to compute functional diversity indices

**`FD::dbFD()`** is probably the most known function to compute functional diversity indices. It comes from the `FD` package proposed by @Laliberte_FD_2014. It can compute many indices: functional richness, Rao's quadratic entropy, community-weighted mean, functional divergence, functional dispersion, and functional group richness. This swiss-army knife of functional diversity indices has many options and compute several indices in a single run.

**`hillR::hill_func()`** comes from the `hillR` package that computes Hill numbers for taxonomic, functional, and functional diversity [@Li_hillR_2018]. It implements indices proposed by @Chao_Unifying_2014. It computes Rao's quadratic entropy, the mean functional diversity per species, as well as the total functional diversity.

**`adiv::QE()`** comes from the `adiv` package which proposes a toolkit to analyze biodiversity [@Pavoine_adiv_2020]. This function computes Rao's quadratic entropy.

**`SYNCSA::rao.diversity()`** comes from `SYNCSA` package which proposes a simulation framework for meta-communities [@Debastiani_SYNCSA_2012]. The function computes Rao's quadratic entropy as well as functional redundancy.

# Benchmark

We will now benchmark the functions included in `fundiversity` with the corresponding function in other packages using the `microbenchmark::microbenchmark()` function.


```r
tictoc::tic()
library(fundiversity)
data("traits_birds", package = "fundiversity")
data("site_sp_birds", package = "fundiversity")

dist_traits_birds <- dist(traits_birds)
```

With the fairly small (~220 species, 8 sites, 4 traits) provided dataset in `fundiversity`:


```r
microbenchmark::microbenchmark(
  fundiversity = {
    fundiversity::fd_raoq(traits = NULL, site_sp_birds, dist_traits_birds)
  },
  adiv = {
    adiv::QE(site_sp_birds, dis = dist_traits_birds)
  },
  hillR = {
    hillR::hill_func(site_sp_birds, dist_traits_birds, traits_as_is = TRUE)[1, ]
  },
  SYNCSA = {
    SYNCSA::rao.diversity(site_sp_birds,
                          phylodist = as.matrix(dist_traits_birds),
                          standardize = FALSE)$PhyRao
  },
  FD = {
    suppressMessages(
      FD::dbFD(x = dist_traits_birds, a = site_sp_birds, stand.x = FALSE,
               calc.FRic = TRUE, calc.CWM = FALSE, calc.FDiv = FALSE,
               calc.FGR = FALSE, m = "max", stand.FRic = FALSE))
  },
  times = 200
)
#> Registered S3 method overwritten by 'httr':
#>   method           from  
#>   print.cache_info hoardr
#> Registered S3 method overwritten by 'spdep':
#>   method   from
#>   plot.mst ape
#> Registered S3 methods overwritten by 'adegraphics':
#>   method         from
#>   biplot.dudi    ade4
#>   kplot.foucart  ade4
#>   kplot.mcoa     ade4
#>   kplot.mfa      ade4
#>   kplot.pta      ade4
#>   kplot.sepan    ade4
#>   kplot.statis   ade4
#>   scatter.coa    ade4
#>   scatter.dudi   ade4
#>   scatter.nipals ade4
#>   scatter.pco    ade4
#>   score.acm      ade4
#>   score.mix      ade4
#>   score.pca      ade4
#>   screeplot.dudi ade4
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'. 
#> FRic: No dimensionality reduction was required. All 3 PCoA axes were kept as 'traits'.
#> Unit: milliseconds
#>          expr         min          lq        mean      median         uq        max neval
#>  fundiversity    1.851354    2.542076    3.365577    2.791778    3.04240   38.14967   200
#>          adiv   12.792653   16.816339   55.450231   18.243288   29.86532 5768.08026   200
#>         hillR   29.956149   34.316934   38.575301   35.670645   37.93952   65.61948   200
#>        SYNCSA  125.443289  134.822229  155.041107  139.802255  153.00069 1704.38972   200
#>            FD 3532.270819 3724.509356 3806.177318 3776.269202 3808.17436 4507.80683   200
```


## Increasing the number of species


```r
make_more_sp <- function(n) {
  traits <- do.call(rbind, replicate(n, traits_birds, simplify = FALSE))
  row.names(traits) <- paste0("sp", seq_len(nrow(traits)))

  site_sp <- do.call(cbind, replicate(n, site_sp_birds, simplify = FALSE))
  colnames(site_sp) <- paste0("sp", seq_len(ncol(site_sp)))

  list(tr = traits, si = site_sp)
}

null_sp_1000   <- make_more_sp(5)
null_sp_10000  <- make_more_sp(50)
null_sp_100000 <- make_more_sp(500)
```


```r
microbenchmark::microbenchmark(
  species_200    = fd_fric(     traits_birds, site_sp_birds),
  species_1000   = fd_fric(  null_sp_1000$tr, null_sp_1000$si),
  species_10000  = fd_fric( null_sp_10000$tr, null_sp_10000$si),
  species_100000 = fd_fric(null_sp_100000$tr, null_sp_100000$si),
  times = 100
)
#> Unit: milliseconds
#>            expr       min        lq      mean    median        uq        max neval
#>     species_200  10.76294  11.62333  12.44972  12.03686  12.72876   33.22621   100
#>    species_1000  16.29932  16.99070  18.02814  17.48805  18.12360   37.33834   100
#>   species_10000  67.61056  71.21242  82.27261  72.80377  76.38987  415.09088   100
#>  species_100000 658.87513 700.67516 772.14282 714.53837 725.69648 1060.69525   100
```


```r
microbenchmark::microbenchmark(
  species_200    = fd_fdiv(     traits_birds, site_sp_birds),
  species_1000   = fd_fdiv(  null_sp_1000$tr, null_sp_1000$si),
  species_10000  = fd_fdiv( null_sp_10000$tr, null_sp_10000$si),
  species_100000 = fd_fdiv(null_sp_100000$tr, null_sp_100000$si),
  times = 100
)
#> Unit: microseconds
#>            expr        min         lq       mean     median         uq        max neval
#>     species_200    922.623   1006.933   1118.715   1067.642   1184.442   1534.966   100
#>    species_1000   1800.785   1967.479   2517.570   2063.514   2345.487  20611.676   100
#>   species_10000  13731.881  15379.155  23686.937  16648.117  25652.694 349575.552   100
#>  species_100000 281523.065 299145.966 377736.411 311178.407 327716.989 658842.841   100
```


```r
microbenchmark::microbenchmark(
  species_200    = fd_raoq(     traits_birds, site_sp_birds),
  species_1000   = fd_raoq(  null_sp_1000$tr, null_sp_1000$si),
  species_10000  = fd_raoq( null_sp_10000$tr, null_sp_10000$si),
  times = 100
)
#> Unit: milliseconds
#>           expr          min           lq         mean       median           uq          max neval
#>    species_200     1.939792     2.683184     3.140481     3.209565     3.604634     4.503351   100
#>   species_1000    65.511345    77.482245    87.384007    91.956021    94.771501   102.199256   100
#>  species_10000 11507.284679 12083.469165 12219.250343 12193.617353 12298.252644 13788.846889   100
```

## Increasing the number of sites


```r
make_more_sites <- function(n) {
  site_sp <- do.call(rbind, replicate(n, site_sp_birds, simplify = FALSE))
  rownames(site_sp) <- paste0("s", seq_len(nrow(site_sp)))

  site_sp
}

site_sp_100   <- make_more_sites(12)
site_sp_1000  <- make_more_sites(120)
site_sp_10000 <- make_more_sites(1200)
```


```r
microbenchmark::microbenchmark(
  sites_10    = fd_fric(traits_birds, site_sp_birds),
  sites_100   = fd_fric(traits_birds, site_sp_100),
  sites_1000  = fd_fric(traits_birds, site_sp_1000),
  sites_10000 = fd_fric(traits_birds, site_sp_10000),
  times = 100
)
#> Unit: milliseconds
#>         expr        min          lq        mean      median          uq         max neval
#>     sites_10    10.9185    12.05121    14.17099    12.87236    14.82578    27.72141   100
#>    sites_100   132.1644   140.84784   161.67556   149.90241   172.00912   320.97972   100
#>   sites_1000  1339.8927  1437.91395  1575.44224  1525.65797  1641.65260  2128.72415   100
#>  sites_10000 14018.8311 15012.69823 16154.88210 15408.78725 17487.24474 24961.83631   100
```


```r
microbenchmark::microbenchmark(
  sites_10    = fd_fdiv(traits_birds, site_sp_birds),
  sites_100   = fd_fdiv(traits_birds, site_sp_100),
  sites_1000  = fd_fdiv(traits_birds, site_sp_1000),
  sites_10000 = fd_fdiv(traits_birds, site_sp_10000),
  times = 100
)
#> Unit: microseconds
#>         expr        min         lq       mean     median         uq         max neval
#>     sites_10    978.697   1103.675   1268.132   1183.312   1415.331    2555.331   100
#>    sites_100   6452.074   7667.274  11889.898   8195.945   9213.770  145204.433   100
#>   sites_1000  66256.557  73591.984  84025.394  76426.329  82809.934  244538.251   100
#>  sites_10000 769836.433 837475.358 868610.774 859412.459 889204.755 1269670.008   100
```


```r
microbenchmark::microbenchmark(
  sites_10    = fd_raoq(traits = NULL, site_sp_birds, dist_traits_birds),
  sites_100   = fd_raoq(traits = NULL, site_sp_100,   dist_traits_birds),
  sites_1000  = fd_raoq(traits = NULL, site_sp_1000,  dist_traits_birds),
  sites_10000 = fd_raoq(traits = NULL, site_sp_10000, dist_traits_birds),
  times = 100
)
#> Unit: milliseconds
#>         expr          min           lq         mean       median           uq          max neval
#>     sites_10     1.499525     2.088144     2.480647     2.494496     2.725040     3.684319   100
#>    sites_100     6.443244     7.566733     8.291933     8.081411     8.982254    11.023804   100
#>   sites_1000   179.060921   201.041081   212.259842   208.973225   216.875272   606.465796   100
#>  sites_10000 16896.036539 17939.155262 18255.608318 18411.737917 18674.157952 19293.420115   100
```

<details>
<summary>Session info of the machine on which the benchmark was ran and time it took to run</summary>

```r
tictoc::toc()
#> 5909.941 sec elapsed
sessioninfo::session_info()
#> ─ Session info ─────────────────────────────────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       macOS High Sierra 10.13.6   
#>  system   x86_64, darwin17.0          
#>  ui       RStudio                     
#>  language (EN)                        
#>  collate  fr_FR.UTF-8                 
#>  ctype    fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-12-20                  
#> 
#> ─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────
#>  package           * version    date       lib source        
#>  abind               1.4-5      2016-07-21 [1] CRAN (R 4.0.2)
#>  ade4                1.7-16     2020-10-28 [1] CRAN (R 4.0.2)
#>  adegenet            2.1.3      2020-05-10 [1] CRAN (R 4.0.2)
#>  adegraphics         1.0-15     2018-12-18 [1] CRAN (R 4.0.2)
#>  adephylo            1.1-11     2017-12-18 [1] CRAN (R 4.0.2)
#>  adiv                2.0.1      2020-08-26 [1] CRAN (R 4.0.2)
#>  ape                 5.4-1      2020-08-13 [1] CRAN (R 4.0.2)
#>  assertthat          0.2.1      2019-03-21 [1] CRAN (R 4.0.2)
#>  boot                1.3-25     2020-04-26 [1] CRAN (R 4.0.3)
#>  callr               3.5.1      2020-10-13 [1] CRAN (R 4.0.2)
#>  class               7.3-17     2020-04-26 [1] CRAN (R 4.0.3)
#>  classInt            0.4-3      2020-04-07 [1] CRAN (R 4.0.2)
#>  cli                 2.2.0      2020-11-20 [1] CRAN (R 4.0.3)
#>  cluster             2.1.0      2019-06-19 [1] CRAN (R 4.0.3)
#>  clusterGeneration   1.3.7      2020-12-15 [1] CRAN (R 4.0.3)
#>  coda                0.19-4     2020-09-30 [1] CRAN (R 4.0.2)
#>  codetools           0.2-18     2020-11-04 [1] CRAN (R 4.0.2)
#>  colorspace          2.0-0      2020-11-11 [1] CRAN (R 4.0.2)
#>  combinat            0.0-8      2012-10-29 [1] CRAN (R 4.0.2)
#>  crayon              1.3.4      2017-09-16 [1] CRAN (R 4.0.2)
#>  crosstalk           1.1.0.1    2020-03-13 [1] CRAN (R 4.0.2)
#>  crul                1.0.0      2020-07-30 [1] CRAN (R 4.0.2)
#>  curl                4.3        2019-12-02 [1] CRAN (R 4.0.1)
#>  DBI                 1.1.0      2019-12-15 [1] CRAN (R 4.0.2)
#>  deldir              0.2-3      2020-11-09 [1] CRAN (R 4.0.2)
#>  desc                1.2.0      2018-05-01 [1] CRAN (R 4.0.2)
#>  devtools            2.3.2      2020-09-18 [1] CRAN (R 4.0.2)
#>  digest              0.6.27     2020-10-24 [1] CRAN (R 4.0.2)
#>  dplyr               1.0.2      2020-08-18 [1] CRAN (R 4.0.2)
#>  DT                  0.16       2020-10-13 [1] CRAN (R 4.0.2)
#>  e1071               1.7-4      2020-10-14 [1] CRAN (R 4.0.2)
#>  ellipsis            0.3.1      2020-05-15 [1] CRAN (R 4.0.2)
#>  evaluate            0.14       2019-05-28 [1] CRAN (R 4.0.1)
#>  expm                0.999-5    2020-07-20 [1] CRAN (R 4.0.2)
#>  FactoMineR          2.4        2020-12-11 [1] CRAN (R 4.0.3)
#>  fansi               0.4.1      2020-01-08 [1] CRAN (R 4.0.2)
#>  fastmap             1.0.1      2019-10-08 [1] CRAN (R 4.0.2)
#>  fastmatch           1.1-0      2017-01-28 [1] CRAN (R 4.0.2)
#>  FD                  1.0-12     2014-08-19 [1] CRAN (R 4.0.2)
#>  flashClust          1.01-2     2012-08-21 [1] CRAN (R 4.0.2)
#>  fs                  1.5.0      2020-07-31 [1] CRAN (R 4.0.2)
#>  fundiversity      * 0.0.0.9000 2020-12-20 [1] local         
#>  gdata               2.18.0     2017-06-06 [1] CRAN (R 4.0.2)
#>  generics            0.1.0      2020-10-31 [1] CRAN (R 4.0.2)
#>  geometry            0.4.5      2019-12-04 [1] CRAN (R 4.0.2)
#>  ggplot2             3.3.2      2020-06-19 [1] CRAN (R 4.0.2)
#>  ggrepel             0.9.0      2020-12-16 [1] CRAN (R 4.0.3)
#>  glue                1.4.2      2020-08-27 [1] CRAN (R 4.0.2)
#>  gmodels             2.18.1     2018-06-25 [1] CRAN (R 4.0.2)
#>  gtable              0.3.0      2019-03-25 [1] CRAN (R 4.0.2)
#>  gtools              3.8.2      2020-03-31 [1] CRAN (R 4.0.2)
#>  hillR               0.5.0      2020-07-07 [1] CRAN (R 4.0.2)
#>  hms                 0.5.3      2020-01-08 [1] CRAN (R 4.0.2)
#>  hoardr              0.5.2      2018-12-02 [1] CRAN (R 4.0.2)
#>  htmltools           0.5.0      2020-06-16 [1] CRAN (R 4.0.2)
#>  htmlwidgets         1.5.3      2020-12-10 [1] CRAN (R 4.0.3)
#>  httpcode            0.3.0      2020-04-10 [1] CRAN (R 4.0.2)
#>  httpuv              1.5.4      2020-06-06 [1] CRAN (R 4.0.2)
#>  httr                1.4.2      2020-07-20 [1] CRAN (R 4.0.2)
#>  igraph              1.2.6      2020-10-06 [1] CRAN (R 4.0.2)
#>  jpeg                0.1-8.1    2019-10-24 [1] CRAN (R 4.0.2)
#>  jsonlite            1.7.2      2020-12-09 [1] CRAN (R 4.0.3)
#>  KernSmooth          2.23-18    2020-10-29 [1] CRAN (R 4.0.2)
#>  knitr               1.30       2020-09-22 [1] CRAN (R 4.0.2)
#>  later               1.1.0.1    2020-06-05 [1] CRAN (R 4.0.2)
#>  lattice             0.20-41    2020-04-02 [1] CRAN (R 4.0.3)
#>  latticeExtra        0.6-29     2019-12-19 [1] CRAN (R 4.0.2)
#>  lazyeval            0.2.2      2019-03-15 [1] CRAN (R 4.0.2)
#>  leaps               3.1        2020-01-16 [1] CRAN (R 4.0.2)
#>  LearnBayes          2.15.1     2018-03-18 [1] CRAN (R 4.0.2)
#>  lifecycle           0.2.0      2020-03-06 [1] CRAN (R 4.0.2)
#>  magic               1.5-9      2018-09-17 [1] CRAN (R 4.0.2)
#>  magrittr            2.0.1      2020-11-17 [1] CRAN (R 4.0.2)
#>  manipulateWidget    0.10.1     2020-02-24 [1] CRAN (R 4.0.2)
#>  maps                3.3.0      2018-04-03 [1] CRAN (R 4.0.2)
#>  MASS                7.3-53     2020-09-09 [1] CRAN (R 4.0.3)
#>  Matrix              1.2-18     2019-11-27 [1] CRAN (R 4.0.3)
#>  memoise             1.1.0      2017-04-21 [1] CRAN (R 4.0.2)
#>  mgcv                1.8-33     2020-08-27 [1] CRAN (R 4.0.3)
#>  microbenchmark      1.4-7      2019-09-24 [1] CRAN (R 4.0.2)
#>  mime                0.9        2020-02-04 [1] CRAN (R 4.0.2)
#>  miniUI              0.1.1.1    2018-05-18 [1] CRAN (R 4.0.2)
#>  mnormt              2.0.2      2020-09-01 [1] CRAN (R 4.0.2)
#>  munsell             0.5.0      2018-06-12 [1] CRAN (R 4.0.2)
#>  nlme                3.1-151    2020-12-10 [1] CRAN (R 4.0.3)
#>  numDeriv            2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.2)
#>  permute             0.9-5      2019-03-12 [1] CRAN (R 4.0.2)
#>  phangorn            2.5.5      2019-06-19 [1] CRAN (R 4.0.2)
#>  phylobase           0.8.10     2020-03-01 [1] CRAN (R 4.0.2)
#>  phytools            0.7-70     2020-09-19 [1] CRAN (R 4.0.2)
#>  pillar              1.4.7      2020-11-20 [1] CRAN (R 4.0.3)
#>  pkgbuild            1.2.0      2020-12-15 [1] CRAN (R 4.0.3)
#>  pkgconfig           2.0.3      2019-09-22 [1] CRAN (R 4.0.2)
#>  pkgload             1.1.0      2020-05-29 [1] CRAN (R 4.0.2)
#>  plotrix             3.7-8      2020-04-16 [1] CRAN (R 4.0.2)
#>  plyr                1.8.6      2020-03-03 [1] CRAN (R 4.0.2)
#>  png                 0.1-7      2013-12-03 [1] CRAN (R 4.0.2)
#>  prettyunits         1.1.1      2020-01-24 [1] CRAN (R 4.0.2)
#>  processx            3.4.5      2020-11-30 [1] CRAN (R 4.0.3)
#>  progress            1.2.2      2019-05-16 [1] CRAN (R 4.0.2)
#>  promises            1.1.1      2020-06-09 [1] CRAN (R 4.0.2)
#>  ps                  1.5.0      2020-12-05 [1] CRAN (R 4.0.2)
#>  purrr               0.3.4      2020-04-17 [1] CRAN (R 4.0.2)
#>  quadprog            1.5-8      2019-11-20 [1] CRAN (R 4.0.2)
#>  R6                  2.5.0      2020-10-28 [1] CRAN (R 4.0.2)
#>  rappdirs            0.3.1      2016-03-28 [1] CRAN (R 4.0.2)
#>  raster              3.4-5      2020-11-14 [1] CRAN (R 4.0.2)
#>  RColorBrewer        1.1-2      2014-12-07 [1] CRAN (R 4.0.2)
#>  Rcpp                1.0.5      2020-07-06 [1] CRAN (R 4.0.2)
#>  RcppArmadillo       0.10.1.2.0 2020-11-16 [1] CRAN (R 4.0.2)
#>  rdryad              1.0.0      2020-06-25 [1] CRAN (R 4.0.2)
#>  remotes             2.2.0      2020-07-21 [1] CRAN (R 4.0.2)
#>  reshape2            1.4.4      2020-04-09 [1] CRAN (R 4.0.2)
#>  rgl                 0.103.5    2020-11-23 [1] CRAN (R 4.0.3)
#>  rlang               0.4.9      2020-11-26 [1] CRAN (R 4.0.3)
#>  rmarkdown           2.6        2020-12-14 [1] CRAN (R 4.0.2)
#>  rncl                0.8.4      2020-02-10 [1] CRAN (R 4.0.2)
#>  RNeXML              2.4.5      2020-06-18 [1] CRAN (R 4.0.2)
#>  rprojroot           2.0.2      2020-11-15 [1] CRAN (R 4.0.2)
#>  rstudioapi          0.13       2020-11-12 [1] CRAN (R 4.0.2)
#>  scales              1.1.1      2020-05-11 [1] CRAN (R 4.0.2)
#>  scatterplot3d       0.3-41     2018-03-14 [1] CRAN (R 4.0.2)
#>  seqinr              4.2-5      2020-12-17 [1] CRAN (R 4.0.3)
#>  sessioninfo         1.1.1      2018-11-05 [1] CRAN (R 4.0.2)
#>  sf                  0.9-6      2020-09-13 [1] CRAN (R 4.0.2)
#>  shiny               1.5.0      2020-06-23 [1] CRAN (R 4.0.2)
#>  sp                  1.4-4      2020-10-07 [1] CRAN (R 4.0.2)
#>  spData              0.3.8      2020-07-03 [1] CRAN (R 4.0.2)
#>  spdep               1.1-5      2020-06-29 [1] CRAN (R 4.0.2)
#>  stringi             1.5.3      2020-09-09 [1] CRAN (R 4.0.2)
#>  stringr             1.4.0      2019-02-10 [1] CRAN (R 4.0.2)
#>  SYNCSA              1.3.4      2020-01-09 [1] CRAN (R 4.0.2)
#>  testthat            3.0.1      2020-12-17 [1] CRAN (R 4.0.3)
#>  tibble              3.0.4      2020-10-12 [1] CRAN (R 4.0.2)
#>  tictoc              1.0        2014-06-17 [1] CRAN (R 4.0.2)
#>  tidyr               1.1.2      2020-08-27 [1] CRAN (R 4.0.2)
#>  tidyselect          1.1.0      2020-05-11 [1] CRAN (R 4.0.2)
#>  tmvnsim             1.0-2      2016-12-15 [1] CRAN (R 4.0.2)
#>  units               0.6-7      2020-06-13 [1] CRAN (R 4.0.2)
#>  usethis             2.0.0      2020-12-10 [1] CRAN (R 4.0.3)
#>  uuid                0.1-4      2020-02-26 [1] CRAN (R 4.0.2)
#>  vctrs               0.3.6      2020-12-17 [1] CRAN (R 4.0.3)
#>  vegan               2.5-7      2020-11-28 [1] CRAN (R 4.0.2)
#>  webshot             0.5.2      2019-11-22 [1] CRAN (R 4.0.2)
#>  withr               2.3.0      2020-09-22 [1] CRAN (R 4.0.2)
#>  xfun                0.19       2020-10-30 [1] CRAN (R 4.0.2)
#>  XML                 3.99-0.5   2020-07-23 [1] CRAN (R 4.0.2)
#>  xml2                1.3.2      2020-04-23 [1] CRAN (R 4.0.2)
#>  xtable              1.8-4      2019-04-21 [1] CRAN (R 4.0.2)
#>  yaml                2.2.1      2020-02-01 [1] CRAN (R 4.0.2)
#>  zip                 2.1.1      2020-08-27 [1] CRAN (R 4.0.2)
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```
</details>

# References


